service: llama-bridges

package:
  individually: true
  excludeDevDependencies: true
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  region: eu-central-1
  endpointType: REGIONAL # Set to regional because the api gateway will be behind a cloudfront distribution
  stage: prod # Default to dev if no stage is specified
  tracing: # Enable X-Ray tracing (debugging)
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow # X-Ray permissions
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: "Allow"
      Action:
        - rds-data:ExecuteStatement
        - rds-data:BatchExecuteStatement
      Resource:
        - "Fn::Join":
            - ":"
            - - "arn:aws:rds-db"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "db:indexer-instance-1-eu-central-1c"
    - Effect: Allow # Lambda logs on cloudwatch
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "Fn::Join":
            - ":"
            - - "arn:aws:logs"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "log-group:/aws/lambda/*:*:*"
    # For warm-up functions
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:*Object*"
      Resource: "*"
  environment:
    PSQL_URL: ${env:PSQL_URL}
    PSQL_USERNAME: ${env:PSQL_USERNAME}
    PSQL_PW: ${env:PSQL_PW}
    MODE: lambda
    BSC_RPC: ${env:BSC_RPC}
    CELO_RPC: ${env:CELO_RPC}
    ETHEREUM_RPC: ${env:ETHEREUM_RPC}
    OPTIMISM_RPC: ${env:OPTIMISM_RPC}
    AURORA_RPC: ${env:AURORA_RPC}
    ARBITRUM_RPC: ${env:ARBITRUM_RPC}
    SOLANA_RPC: ${env:SOLANA_RPC}

functions:
  bridgeDayStats:
    handler: src/handlers/getBridgeStatsOnDay.default
    timeout: 30
    memorySize: 2000
    events:
      - http:
          path: bridgedaystats/{timestamp}/{chain}
          method: get
  bridgeVolume:
    handler: src/handlers/getBridgeVolume.default
    timeout: 30
    memorySize: 3000
    events:
      - http:
          path: bridgevolume/{chain}
          method: get
  bridges:
    handler: src/handlers/getBridges.default
    timeout: 30
    memorySize: 2000
    events:
      - http:
          path: bridges
          method: get
  bridge:
    handler: src/handlers/getBridge.default
    timeout: 30
    memorySize: 2000
    events:
      - http:
          path: bridge/{id}
          method: get
  transactions:
    handler: src/handlers/getTransactions.default
    timeout: 30
    memorySize: 3000
    events:
      - http:
          path: transactions/{id}
          method: get
  largeTransactions:
    handler: src/handlers/getLargeTransactions.default
    timeout: 30
    memorySize: 3000
    events:
      - http:
          path: largetransactions/{chain}
          method: get
  runAdapter:
    handler: src/handlers/runAdapter.default
    timeout: 900
    memorySize: 1024
  runAllAdapters:
    handler: src/handlers/runAllAdapters.default
    timeout: 900
    memorySize: 250
    events:
      - schedule: cron(2,17,47 * * * ? *)
  runAggregateAllAdapters:
    handler: src/handlers/runAggregateAllAdapters.default
    timeout: 900
    memorySize: 10240
    events:
      - schedule: cron(32 * * * ? *)
  checkDbEntries:
    handler: src/handlers/checkDbEntries.default
    timeout: 600
    memorySize: 2000
    events:
      - schedule: cron(30 1 * * ? *)

resources:
  # CORS for api gateway errors
  - ${file(resources/api-gateway-errors.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: "npm"
    excludeFiles: src/**/*.test.ts
  prune:
    automatic: true
    number: 5 # Number of versions to keep

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
